title: EvoMapJS
description: A JS Toolbox for Mapping Evolving Relationship Data
theme: just-the-docs

url: https://evomapviz.github.io/EvoMapJS/

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/EvoMapViz/EvoMapJS 
